name: Push packages to NuGet.org

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Pack Aperture Core
        run: dotnet pack --configuration Release Aperture.Core
      - name: Push Aperture.Core
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
        run: dotnet nuget push Aperture.Core/bin/Release/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
